---
Name: paymentgatewaysroutes
#After: framework/routes#coreroutes
---
Director:
  rules:
    'pg-payment/poli-complete': 'PoliController'
    'pg-payment/paystation-complete': 'PaystationController'
